<?php /* Smarty version 2.6.27, created on 2017-06-13 11:27:35
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%E4^E48^E4840D95%%tpl_index.html.inc'] = '56648905633cd3511a1fa9ab2a19cc07';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/tpl_index.html', 56, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/tpl_index.html', 61, false),)), $this); ?>
<?php
function _smarty_tplfunc_56648905633cd3511a1fa9ab2a19cc07_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 5,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
