<?php /* Smarty version 2.6.27, created on 2017-08-22 17:01:19
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophia/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%A5^A5D^A5D5CAF3%%tpl_index.html.inc'] = '7016801a2c3ed2293841551f72222849';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophia/tpl_index.html', 56, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophia/tpl_index.html', 61, false),)), $this); ?>
<?php
function _smarty_tplfunc_7016801a2c3ed2293841551f72222849_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 5,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
