<?php /* Smarty version 2.6.27, created on 2017-08-03 16:27:55
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/gmi/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%3A^3A1^3A1D882F%%tpl_index.html.inc'] = '476e0c2ea229668d02ad4fc008c1b119';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/gmi/tpl_index.html', 56, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/gmi/tpl_index.html', 61, false),)), $this); ?>
<?php
function _smarty_tplfunc_476e0c2ea229668d02ad4fc008c1b119_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 5,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
