<?php /* Smarty version 2.6.27, created on 2016-05-11 09:47:55
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/info/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%E0^E0E^E0E4A9EB%%tpl_index.html.inc'] = 'ffee50b5d7661b6729f8c9910bc06056';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/info/tpl_index.html', 32, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/info/tpl_index.html', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_ffee50b5d7661b6729f8c9910bc06056_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 10,'name' => 'info','move' => true,'notdata' => true), $_smarty);
}



?>
