<?php /* Smarty version 2.6.27, created on 2013-08-08 15:22:19
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/info/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%28^281^2812EDAB%%tpl_index.html.inc'] = '36aecd1b181b7a07df93319481f32913';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/info/tpl_index.html', 32, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/info/tpl_index.html', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_36aecd1b181b7a07df93319481f32913_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 1,'max' => 10,'name' => 'info','move' => true,'notdata' => true), $_smarty);
}



?>
