<?php /* Smarty version 2.6.27, created on 2015-08-25 14:22:23
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%D4^D40^D40157D0%%tpl_index.html.inc'] = '75df78574224e17262c9fd090bb5d874';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_index.html', 132, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_index.html', 149, false),array('modifier', 'replace', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_index.html', 149, false),)), $this); ?>
<?php
function _smarty_tplfunc_75df78574224e17262c9fd090bb5d874_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 3,'max' => 4,'name' => 'information','notdata' => true,'move' => false), $_smarty);
}



?>
