<?php /* Smarty version 2.6.27, created on 2015-05-26 11:07:54
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_news.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%FF^FFA^FFA8AA73%%tpl_news.html.inc'] = '9df8b8d22ed1c330f00d24cf11376452';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_news.html', 59, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_news.html', 98, false),array('modifier', 'replace', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_news.html', 98, false),)), $this); ?>
<?php
function _smarty_tplfunc_9df8b8d22ed1c330f00d24cf11376452_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 3,'max' => 10,'name' => 'information','notdata' => true), $_smarty);
}



?>
