<?php /* Smarty version 2.6.27, created on 2017-06-07 20:07:45
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/info/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%A4^A4C^A4C4B4F5%%tpl_index.html.inc'] = 'af08211b650a9f42ca34dc6b68f20f9d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/info/tpl_index.html', 32, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/info/tpl_index.html', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_af08211b650a9f42ca34dc6b68f20f9d_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 10,'name' => 'info','move' => true,'notdata' => true), $_smarty);
}



?>
