<?php /* Smarty version 2.6.27, created on 2013-08-08 15:20:45
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/info/tpl_article.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%3C^3C2^3C2F24FE%%tpl_article.html.inc'] = '53398886a2422e2e3f9820007e552fa0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/info/tpl_article.html', 8, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/info/tpl_article.html', 34, false),)), $this); ?>
<?php
function _smarty_tplfunc_53398886a2422e2e3f9820007e552fa0_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_detail(array('id' => 1), $_smarty);
}



?>
