<?php /* Smarty version 2.6.27, created on 2017-08-04 18:09:31
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/info/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%D6^D61^D611BD6A%%tpl_index.html.inc'] = '5f3e242bab74c5e84ba3347a1fe0a756';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/info/tpl_index.html', 32, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/info/tpl_index.html', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_5f3e242bab74c5e84ba3347a1fe0a756_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 10,'name' => 'info','move' => true,'notdata' => true), $_smarty);
}



?>
