<?php /* Smarty version 2.6.27, created on 2017-06-09 17:35:48
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/info/tpl_article.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%0A^0AA^0AA031A2%%tpl_article.html.inc'] = 'b96b03bfe4695c47caeb3569e6e06d15';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/info/tpl_article.html', 8, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/info/tpl_article.html', 34, false),)), $this); ?>
<?php
function _smarty_tplfunc_b96b03bfe4695c47caeb3569e6e06d15_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_detail(array('id' => 2), $_smarty);
}



?>
