<?php /* Smarty version 2.6.27, created on 2016-05-09 19:05:54
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2/info/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%F3^F36^F36180DF%%tpl_index.html.inc'] = '64adfc0cdba7f671c28f232f06e0090d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2/info/tpl_index.html', 32, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2/info/tpl_index.html', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_64adfc0cdba7f671c28f232f06e0090d_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 1,'max' => 10,'name' => 'info','move' => true,'notdata' => true), $_smarty);
}



?>
