<?php /* Smarty version 2.6.27, created on 2017-08-04 16:07:48
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/search/tpl_detail.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%CC^CC2^CC2CA08D%%tpl_detail.html.inc'] = 'd61a2069e676f9c29d6a0d728d988dd3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'job2_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/search/tpl_detail.html', 41, false),array('modifier', 'nl2br', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/search/tpl_detail.html', 66, false),)), $this); ?>
<?php
function _smarty_tplfunc_d61a2069e676f9c29d6a0d728d988dd3_0(&$_smarty)
{
echo smartyanytime_plugins_job2::job2_detail(array(), $_smarty);
}



?>
