<?php /* Smarty version 2.6.27, created on 2015-10-14 09:46:40
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/search/tpl_detail.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%7F^7FF^7FF350EA%%tpl_detail.html.inc'] = 'c44bccb1473e646aeb1711f689e98ff1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'job2_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/search/tpl_detail.html', 41, false),array('modifier', 'nl2br', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/search/tpl_detail.html', 66, false),)), $this); ?>
<?php
function _smarty_tplfunc_c44bccb1473e646aeb1711f689e98ff1_0(&$_smarty)
{
echo smartyanytime_plugins_job2::job2_detail(array(), $_smarty);
}



?>
