<?php /* Smarty version 2.6.27, created on 2016-05-27 10:17:36
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%33^338^338010DE%%tpl_index.html.inc'] = '54120f2468290ad808f4c4b1488acbc1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/tpl_index.html', 56, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/tpl_index.html', 61, false),)), $this); ?>
<?php
function _smarty_tplfunc_54120f2468290ad808f4c4b1488acbc1_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 5,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
