<?php /* Smarty version 2.6.27, created on 2017-10-12 05:48:41
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/search/tpl_detail.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%68^68C^68CE14BB%%tpl_detail.html.inc'] = '4cba648adca3004255d434e73cbedb96';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'job2_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/search/tpl_detail.html', 41, false),array('modifier', 'nl2br', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/search/tpl_detail.html', 66, false),)), $this); ?>
<?php
function _smarty_tplfunc_4cba648adca3004255d434e73cbedb96_0(&$_smarty)
{
echo smartyanytime_plugins_job2::job2_detail(array(), $_smarty);
}



?>
