<?php /* Smarty version 2.6.27, created on 2016-05-02 18:51:18
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%BD^BDC^BDC5B187%%tpl_index.html.inc'] = '0179c3f13ed0760fa310cc264f9774c9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2/tpl_index.html', 101, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2/tpl_index.html', 106, false),)), $this); ?>
<?php
function _smarty_tplfunc_0179c3f13ed0760fa310cc264f9774c9_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 1,'max' => 9,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
