<?php /* Smarty version 2.6.27, created on 2016-05-11 09:49:08
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/search/tpl_detail.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%CF^CFA^CFA200CA%%tpl_detail.html.inc'] = '80c4f0816dc948d5527c33412fef7280';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'job2_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/search/tpl_detail.html', 41, false),array('modifier', 'nl2br', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi3/search/tpl_detail.html', 66, false),)), $this); ?>
<?php
function _smarty_tplfunc_80c4f0816dc948d5527c33412fef7280_0(&$_smarty)
{
echo smartyanytime_plugins_job2::job2_detail(array(), $_smarty);
}



?>
