<?php /* Smarty version 2.6.27, created on 2017-09-05 15:15:54
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/maxfields/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%23^233^2339CF05%%tpl_index.html.inc'] = 'ad875a7c687c6c0aa66c5400f8e7f079';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/maxfields/tpl_index.html', 100, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/maxfields/tpl_index.html', 105, false),)), $this); ?>
<?php
function _smarty_tplfunc_ad875a7c687c6c0aa66c5400f8e7f079_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 1,'max' => 9,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
