<?php /* Smarty version 2.6.27, created on 2017-08-04 16:50:36
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophiamax/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%11^11D^11D2B908%%tpl_index.html.inc'] = 'c4f531b876e84704db32923bde7d70b4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophiamax/tpl_index.html', 56, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophiamax/tpl_index.html', 61, false),)), $this); ?>
<?php
function _smarty_tplfunc_c4f531b876e84704db32923bde7d70b4_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 5,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
