<?php /* Smarty version 2.6.27, created on 2016-03-07 15:59:52
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi2/search/tpl_detail.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%4E^4E8^4E8765ED%%tpl_detail.html.inc'] = 'd2149461e5cc4fabe49354a7809ac766';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'job2_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi2/search/tpl_detail.html', 41, false),array('modifier', 'nl2br', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi2/search/tpl_detail.html', 66, false),)), $this); ?>
<?php
function _smarty_tplfunc_d2149461e5cc4fabe49354a7809ac766_0(&$_smarty)
{
echo smartyanytime_plugins_job2::job2_detail(array(), $_smarty);
}



?>
