<?php /* Smarty version 2.6.27, created on 2017-10-13 01:46:24
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/info/tpl_article.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%B6^B6D^B6D53660%%tpl_article.html.inc'] = '987acbce57baae2f4fc6a543497db0dd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/info/tpl_article.html', 8, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/info/tpl_article.html', 34, false),)), $this); ?>
<?php
function _smarty_tplfunc_987acbce57baae2f4fc6a543497db0dd_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_detail(array('id' => 2), $_smarty);
}



?>
