<?php /* Smarty version 2.6.27, created on 2017-10-01 21:16:51
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/info/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%4C^4C8^4C8453ED%%tpl_index.html.inc'] = '88c8d44afb9e8d217bd603eaba4e147a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/info/tpl_index.html', 32, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/info/tpl_index.html', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_88c8d44afb9e8d217bd603eaba4e147a_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 10,'name' => 'info','move' => true,'notdata' => true), $_smarty);
}



?>
