<?php /* Smarty version 2.6.27, created on 2017-10-11 15:49:10
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%A6^A63^A63176E0%%tpl_index.html.inc'] = 'a0220bcee09e7f9966fde3d7654e6f73';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/tpl_index.html', 100, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields/tpl_index.html', 105, false),)), $this); ?>
<?php
function _smarty_tplfunc_a0220bcee09e7f9966fde3d7654e6f73_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 1,'max' => 9,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
