<?php /* Smarty version 2.6.27, created on 2017-08-04 16:23:38
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%94^94D^94DA00ED%%tpl_index.html.inc'] = '77bc4ccb5450454193e2b76a8323dcf7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/tpl_index.html', 56, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophiamax/tpl_index.html', 61, false),)), $this); ?>
<?php
function _smarty_tplfunc_77bc4ccb5450454193e2b76a8323dcf7_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 5,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
