<?php /* Smarty version 2.6.27, created on 2016-05-30 11:55:06
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/search/tpl_detail.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%1D^1D1^1D18C220%%tpl_detail.html.inc'] = 'fdb2b54f88985ea7f52ee8d94c5a5d2d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'job2_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/search/tpl_detail.html', 41, false),array('modifier', 'nl2br', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi/search/tpl_detail.html', 66, false),)), $this); ?>
<?php
function _smarty_tplfunc_fdb2b54f88985ea7f52ee8d94c5a5d2d_0(&$_smarty)
{
echo smartyanytime_plugins_job2::job2_detail(array(), $_smarty);
}



?>
