<?php /* Smarty version 2.6.27, created on 2017-08-04 15:46:53
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophiamax/info/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%1E^1EB^1EB8C963%%tpl_index.html.inc'] = '19d0070429c34d04deb139c400d17157';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophiamax/info/tpl_index.html', 32, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/maxfields2017/sophiamax/info/tpl_index.html', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_19d0070429c34d04deb139c400d17157_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 10,'name' => 'info','move' => true,'notdata' => true), $_smarty);
}



?>
