<?php /* Smarty version 2.6.27, created on 2015-05-26 11:12:49
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_news_detail.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%A6^A61^A612D11C%%tpl_news_detail.html.inc'] = 'b26354d4dec199bc935e89671d87e9fa';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_news_detail.html', 3, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_news_detail.html', 75, false),array('modifier', 'replace', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_news_detail.html', 75, false),)), $this); ?>
<?php
function _smarty_tplfunc_b26354d4dec199bc935e89671d87e9fa_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_detail(array('id' => 3), $_smarty);
}



?>
