<?php /* Smarty version 2.6.27, created on 2015-05-26 11:27:08
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_job_detail.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%20^208^2088E93A%%tpl_job_detail.html.inc'] = '257126c85c426a0decea98b33fb225d8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'job_detail', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_job_detail.html', 3, false),array('modifier', 'nl2br', 'file:/var/www/vhosts/evolve-max.com/httpdocs/myjobis/tpl_job_detail.html', 88, false),)), $this); ?>
<?php
function _smarty_tplfunc_257126c85c426a0decea98b33fb225d8_0(&$_smarty)
{
echo smartyanytime_plugins_job::job_detail(array(), $_smarty);
}



?>
