<?php /* Smarty version 2.6.27, created on 2017-10-02 10:28:07
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%A2^A23^A23BF605%%tpl_index.html.inc'] = '4651374fe72cfed6a39e6bc12a2e8cdd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/tpl_index.html', 56, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/sophia/tpl_index.html', 61, false),)), $this); ?>
<?php
function _smarty_tplfunc_4651374fe72cfed6a39e6bc12a2e8cdd_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 5,'name' => 'info','move' => false,'notdata' => true), $_smarty);
}



?>
