<?php /* Smarty version 2.6.27, created on 2016-05-24 11:21:12
         compiled from file:/var/www/vhosts/evolve-max.com/httpdocs/gmi2/info/tpl_index.html */

$this->_cache_serials['/var/www/vhosts/evolve-max.com/httpdocs/smartyanytime/templates_c//%2Findex.php^%%7F^7F3^7F3E2A75%%tpl_index.html.inc'] = '12ce2df04a28bb6d9bd111b91f1ff797';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_setlist', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi2/info/tpl_index.html', 32, false),array('modifier', 'd_format', 'file:/var/www/vhosts/evolve-max.com/httpdocs/gmi2/info/tpl_index.html', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_12ce2df04a28bb6d9bd111b91f1ff797_0(&$_smarty)
{
echo smartyanytime_plugins_simplecmsEX::cms_setlist(array('id' => 2,'max' => 10,'name' => 'info','move' => true,'notdata' => true), $_smarty);
}



?>
