<?php
return array(
	'company'=>array(
		'name'=>'会社名',
		'default'=>'',
		'validate'=>array(
			'text'=>array(
				'message'=>':labelを入力して下さい',
			),
			'maxLength'=>array(
				'params'=>50,
				'message'=>':labelは:val1文字以下で入力して下さい',
			),
		)
	),
	'name'=>array(
			'name'=>'お名前',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'maxLength'=>array(
					'params'=>50,
					'message'=>':labelは:val1文字以下で入力して下さい',
				),
			)
	),
	'kana'=>array(
			'name'=>'ふりがな',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'maxLength'=>array(
					'params'=>50,
					'message'=>':labelは:val1文字以下で入力して下さい',
				),
			)
	),
	'tel'=>array(
		'name'=>'電話番号',
		'default'=>'',
		'validate'=>array(
			'require'=>array(
				'params'=>true,
				'message'=>':labelを入力して下さい',
			),
			'text'=>array(
				'message'=>':labelを入力して下さい',
			),
			'tel'=>array(
				'message'=>'正しい:labelを入力して下さい',
			),
			'maxLength'=>array(
				'params'=>20,
				'message'=>':labelは:val1文字以下で入力して下さい',
			),
		)
	),
	'fax'=>array(
		'name'=>'FAX番号',
		'default'=>'',
		'validate'=>array(
			'text'=>array(
				'message'=>':labelを入力して下さい',
			),
			'tel'=>array(
				'allowEmpty'=>true,
				'message'=>'正しい:labelを入力して下さい',
			),
			'maxLength'=>array(
				'allowEmpty'=>true,
				'params'=>20,
				'message'=>':labelは:val1文字以下で入力して下さい',
			),
		)
	),
	'zip'=>array(
			'name'=>'郵便番号',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'zip'=>array(
					'message'=>'正しい:labelを入力して下さい',
				),
			)
	),
	'address'=>array(
			'name'=>'住所',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'maxLength'=>array(
					'params'=>100,
					'message'=>':labelは:val1文字以下で入力して下さい',
				),
			)
	),
	'address2'=>array(
			'name'=>'建物名',
			'default'=>'',
			'validate'=>array(
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'maxLength'=>array(
					'allowEmpty'=>true,
					'params'=>100,
					'message'=>':labelは:val1文字以下で入力して下さい',
				),
			)
	),
	'email'=>array(
			'name'=>'メールアドレス',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'email'=>array(
					'message'=>'正しい:labelを入力して下さい',
				),
				'confirmEmail'=>array(
					'params'=>'email2',
					'message'=>':labelがメールアドレス(確認用)と一致しません',
				),
			)
	),
	'email2'=>array(
			'name'=>'メールアドレス(確認用)',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'email'=>array(
					'message'=>'正しい:labelを入力して下さい',
				),
			)
	),
	'contents'=>array(
			'name'=>'お問い合わせ内容',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'allowEmpty'=>true,
					'message'=>':labelを入力して下さい',
				),
				'maxLength'=>array(
					'params'=>1000,
					'message'=>':labelは:val1文字以下で入力して下さい',
				),
			)
	),
	'privacy-policy'=>array(
		'name'=>'個人情報取り扱い',
		'list'=>array('同意'),
		'default'=>'',
		'validate'=>array(
			'select'=>array(
				'allowEmpty'=>false,
				'message'=>':label をチェックして下さい',
			)
		)
	),
);
