<?php
return array(
	'name'=>array(
			'name'=>'氏名（漢字）',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'maxLength'=>array(
					'params'=>50,
					'message'=>':labelは:val1文字以下で入力して下さい',
				),
			)
	),
	'kana'=>array(
			'name'=>'氏名（フリガナ）',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'maxLength'=>array(
					'params'=>50,
					'message'=>':labelは:val1文字以下で入力して下さい',
				),
			)
	),
	'age'=>array(
		'name'=>'年齢',
		'default'=>'',
		'validate'=>array(
			'require'=>array(
				'params'=>true,
				'message'=>':labelを入力して下さい',
			),
			'text'=>array(
				'message'=>':labelを入力して下さい',
			),
			'maxLength'=>array(
				'params'=>50,
				'message'=>':labelは:val1文字以下で入力して下さい',
			),
		)
	),
	'sex'=>array(
		'name'=>'性別',
		'list'=>array('男性', '女性'),
		'default'=>'',
		'validate'=>array(
			'require'=>array(
				'params'=>true,
				'message'=>':label を選択して下さい',
			),
			'select'=>array(
				'message'=>':label を選択して下さい',
			)
		)
	),
	'tel'=>array(
		'name'=>'連絡先',
		'default'=>'',
		'validate'=>array(
			'require'=>array(
				'params'=>true,
				'message'=>':labelを入力して下さい',
			),
			'text'=>array(
				'message'=>':labelを入力して下さい',
			),
			'tel'=>array(
				'message'=>'正しいお電話番号を入力して下さい',
			),
			'maxLength'=>array(
				'params'=>20,
				'message'=>':labelは:val1文字以下で入力して下さい',
			),
		)
	),
	'zip'=>array(
			'name'=>'郵便番号',
			'default'=>'',
			'validate'=>array(
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'zip'=>array(
					'allowEmpty'=>true,
					'message'=>'正しい:labelを入力して下さい',
				),
			)
	),
	'address'=>array(
			'name'=>'住所',
			'default'=>'',
			'validate'=>array(
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'maxLength'=>array(
					'params'=>100,
					'message'=>':labelは:val1文字以下で入力して下さい',
				),
			)
	),
	'start_date'=>array(
		'name'=>'就業開始可能日',
		'default'=>'',
		'validate'=>array(
			'text'=>array(
				'message'=>':labelを入力して下さい',
			),
			'maxLength'=>array(
				'params'=>50,
				'message'=>':labelは:val1文字以下で入力して下さい',
			),
		)
	),
	'commute'=>array(
		'name'=>'通勤手段',
		'default'=>'',
		'validate'=>array(
			'text'=>array(
				'message'=>':labelを入力して下さい',
			),
			'maxLength'=>array(
				'params'=>50,
				'message'=>':labelは:val1文字以下で入力して下さい',
			),
		)
	),
	'status_work'=>array(
		'name'=>'現況',
		'list'=>array('休職中', '就業中', 'その他'),
		'default'=>'',
		'validate'=>array(
			'select'=>array(
				'allowEmpty'=>true,
				'message'=>':label を選択して下さい',
			)
		)
	),
	'email'=>array(
			'name'=>'メールアドレス',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'email'=>array(
					'message'=>'正しい:labelを入力して下さい',
				),
				'confirmEmail'=>array(
					'params'=>'email2',
					'message'=>':labelがメールアドレス(確認用)と一致しません',
				),
			)
	),
	'email2'=>array(
			'name'=>'メールアドレス(確認用)',
			'default'=>'',
			'validate'=>array(
				'require'=>array(
					'params'=>true,
					'message'=>':labelを入力して下さい',
				),
				'text'=>array(
					'message'=>':labelを入力して下さい',
				),
				'email'=>array(
					'message'=>'正しい:labelを入力して下さい',
				),
			)
	),
	'privacy-policy'=>array(
		'name'=>'個人情報取り扱い',
		'list'=>array('同意'),
		'default'=>'',
		'validate'=>array(
			'select'=>array(
				'allowEmpty'=>false,
				'message'=>':label の同意がなされておりません',
			)
		)
	),
);
